spring:
  main:
    banner-mode: off
  profiles:
    active: dev
  application:
    name: boot
# Tomcat
server:
  port: 28080
  tomcat:
    connection-timeout: 5000ms
    max-threads: 1000
    min-spare-threads: 30

#datasource

# Mybatis-Plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: assign_id
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.base.boot.sys.entity
